<h3 class="text-center title"><?php echo $this->translate('Entrar'); ?></h3>
<form class="m-t" action="<?php echo $this->url('login/autenticar') ?>" class="validate-form" method="post">
	<div class="form-group">
		<div class="controls with-icon-over-input">
			<input value="" placeholder="<?php echo $this->translate('Email'); ?>" class="form-control" data-rule-required="true" name="usuario" type="text" />
			<i class="fa fa-user fa-fw"></i>
		</div>
	</div>
	<div class="form-group">
		<div class="controls with-icon-over-input">
			<input value="" placeholder="<?php echo $this->translate('Senha'); ?>" class="form-control" data-rule-required="true" name="senha" type="password" />
			<i class="fa fa-lock fa-fw"></i>
		</div>
	</div>
	<div class="checkbox i-checks">
		<label for="rememberme">
			<input id="rememberme" name="rememberme" type="checkbox" value="1">
			<?php echo $this->translate('Manter Conectado'); ?>
		</label>
	</div>
	<button class="btn btn-primary block full-width m-b"><?php echo $this->translate('Entrar'); ?></button>
	
	<a href="<?php echo $this->url('login/esqueci') ?>"><small><?php echo $this->translate('Esqueceu a senha?'); ?></small></a>
</form>
