<main class="login">
	<div class="container">
		<div class="col-left">
			<h2><?php echo $this->translate('Sou cadastrado'); ?></h2>
			<form action="<?php echo $this->url('login/autenticar') ?>" class="validate-form" method="post">
				<label for="email"><?php echo $this->translate('E-mail'); ?>:</label>
				<input type="text" id="email" name="usuario">
				<label for="senha"><?php echo $this->translate('Senha'); ?>:</label>
				<input type="password" id="senha" name="senha">
				<a href="<?php echo $this->url('login/esqueci'); ?>"><?php echo $this->translate('Esqueci minha senha'); ?></a>
				<input type="submit" value="<?php echo $this->translate('Entrar'); ?>">
			</form>
		</div>
		<div class="col-right">
			<h2><?php echo $this->translate('Não sou cadastrado'); ?></h2>
			<div class="bannercadastro"></div>
			<input type="button" onclick="window.location = '<?php echo $this->url('cadastre'); ?>'" value="<?php echo $this->translate('Cadastrar'); ?>">
		</div>
	</div>
</main>