<main class="login">
	<div class="container">
		<div class="col-full">
			<form action="" method="post">
				<h2><?php echo $this->translate('Esqueci a senha'); ?></h2>
				
				<label for="senha"><?php echo $this->translate('Senha:'); ?></label>
				<input id="senha" name="senha" type="password" value="">
				
				<label for="confirmaSenha"><?php echo $this->translate('Confirma Senha:'); ?></label>
				<input id="confirmaSenha" name="confirmaSenha" type="password" value="">
				
				<input name="submit" type="submit" value="<?php echo $this->translate('Enviar'); ?>">
			</form>
		</div>
	</div>
</main>