<main class="login">
	<div class="container">
		<div class="col-full">
			<form action="<?php echo $this->url('login/esqueci') ?>" method="post">
				<h2><?php echo $this->translate('Esqueci a senha'); ?></h2>
				
				<label for="email"><?php echo $this->translate('E-mail:'); ?></label>
				<input id="email" name="email" type="text" value="">
				
				<input name="submit" type="submit" value="<?php echo $this->translate('Enviar'); ?>">
			</form>
		</div>
	</div>
</main>