<div class="panel panel-default panel-collapse-pad">
	<div class="panel-heading">
		<h6 class="panel-title">
			<a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" class="collapsed" style="display: block;">
				<i class="icon-search"></i>
				<?php echo $this->translate('Pesquisar'); ?>
			</a>
		</h6>
	</div>
	<div id="collapseTwo" class="panel-collapse collapse">
		<div class="panel-body">
			<?php echo $this->partial('layout/form', array('form' => $this->form, 'actionUrl' => '')); ?>
		</div>
	</div>
</div>

<hr />
<?php
$order = "";
$contOrder = 0;
foreach($this->gridHeaders as $c) {
	if($c->getDefaultSort()) {
		$order = " data-order=\"[[ " . $contOrder . ", &quot;" . $c->getDefaultSortType() . "&quot; ]]\"";
	}
	
	$contOrder++;
}
?>
<div class="table-responsive">
	<table class="table table-striped table-bordered table-hover dataTables-app" width="100%" data-function-get="obterParametros" data-ajax-url="<?php echo $this->form->getActionBuscar(); ?>" data-pagination-records="25"<?php echo $order; ?>>
		<thead>
			<tr>
				<?php foreach($this->gridHeaders as $c): ?>
				<th align="center" <?= $c->getWidth() > 0 ? ' width="' . $c->getWidth() . '"' : '' ?><?= !$c->getSort() ? '  class="nosort"' : '' ?>><?php echo $c->getName(); ?></th>
				<?php endforeach; ?>
			</tr>
		</thead>
		<tbody>
		</tbody>
	</table>
</div>

<?php
$this->inlineScript()->captureStart();
?>
function obterParametros(d) {
	<?php foreach($this->form as $element): ?>
	d.<?= $element->getName(); ?> = $('#<?= $element->getName(); ?>').val();
	<?php endforeach; ?>
}
<?php
$this->inlineScript()->captureEnd();
?>