<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<?php echo $this->headTitle($this->translate('Skeleton'))->setSeparator(' - ')->setAutoEscape(false) ?>

<link href="<?php echo $this->basePath(); ?>/inspinia/css/bootstrap.min.css" rel="stylesheet">
<link href="<?php echo $this->basePath(); ?>/inspinia/font-awesome/css/font-awesome.min.css" rel="stylesheet">

<!-- Data Tables -->
<link href="<?php echo $this->basePath(); ?>/inspinia/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="<?php echo $this->basePath(); ?>/inspinia/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
<link href="<?php echo $this->basePath(); ?>/inspinia/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">

<!-- Select2 -->
<link href="<?php echo $this->basePath(); ?>/app/css/plugins/select2/select2.css" rel="stylesheet">
<link href="<?php echo $this->basePath(); ?>/app/css/plugins/select2/select2-bootstrap.css" rel="stylesheet">

<!-- iCheck style -->
<link href="<?php echo $this->basePath(); ?>/inspinia/css/plugins/iCheck/custom.css" rel="stylesheet">

<!-- Toastr style -->
<link href="<?php echo $this->basePath(); ?>/inspinia/css/plugins/toastr/toastr.min.css" rel="stylesheet">

<!-- Switchery -->
<link href="<?php echo $this->basePath(); ?>/inspinia/css/plugins/switchery/switchery.css" rel="stylesheet">

<link href="<?php echo $this->basePath(); ?>/inspinia/css/animate.css" rel="stylesheet">
<link href="<?php echo $this->basePath(); ?>/inspinia/css/style.css" rel="stylesheet">

<!-- CodeMirror -->
<link href="<?php echo $this->basePath(); ?>/inspinia/css/plugins/codemirror/codemirror.css" rel="stylesheet">
<link href="<?php echo $this->basePath(); ?>/inspinia/css/plugins/codemirror/ambiance.css" rel="stylesheet">

<!-- Date Picker -->
<link href="<?php echo $this->basePath(); ?>/inspinia/css/plugins/datapicker/datepicker3.css" rel="stylesheet">

<!-- Spinner -->
<link href="<?php echo $this->basePath(); ?>/app/css/plugins/spinner/bootstrap-spinner.css" rel="stylesheet">

<!-- App script -->
<link href="<?php echo $this->basePath(); ?>/app/css/app.css" rel="stylesheet">

<?php echo $this->headLink(); ?>

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
