<?php echo $this->doctype(); ?>

<html lang="<?php echo $this->translate('pt-br'); ?>">
	<head>
		<?php echo $this->partial('layout/head', $this); ?>
	</head>

<?php
$children = $this->viewModel()->getCurrent()->getChildren();
$child = $children[0];
$identity = $this->userIdentity();
?>
	<body>
		<input type="hidden" name="baseUrl" id="baseUrl" value="<?php echo $this->basePath(); ?>" />
		<input type="hidden" name="default-locale" id="default-locale" value="<?php echo $this->translate('pt-BR'); ?>" />
		<div id="wrapper">
			<nav class="navbar-default navbar-static-side" role="navigation">
				<div class="sidebar-collapse">
					<ul class="nav" id="side-menu">
						<li class="nav-header">
							<div class="dropdown profile-element">
								<a data-toggle="dropdown" class="dropdown-toggle" href="#">
									<span class="clear">
										<span class="block m-t-xs">
											<strong class="font-bold"><?php echo $identity ? $identity["usuario"]->getNome() : ''; ?></strong>
											<b class="caret"></b>
										</span>
									</span>
								</a>
								
								<ul class="dropdown-menu animated fadeInRight m-t-xs">
									<li><a href="profile.html"><?php echo $this->translate('Perfil'); ?></a></li>
									<li class="divider"></li>
									<li><a href="<?php echo $this->url('login/sair'); ?>"><?php echo $this->translate('Sair'); ?></a></li>
								</ul>
							</div>
							<div class="logo-element">M+</div>
						</li>
						
						<?php echo $this->partial('layout/menu', $this); ?>
					</ul>
				</div>
			</nav>
			
			<div id="page-wrapper" class="gray-bg">
				<div class="row border-bottom">
					<nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
						<div class="navbar-header">
							<a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
						</div>
						
						<ul class="nav navbar-top-links navbar-right">
							<li>
								<a href="<?php echo $this->url('login/sair'); ?>">
									<i class="fa fa-sign-out"></i>
									<?php echo $this->translate('Sair'); ?>
								</a>
							</li>
						</ul>
					</nav>
				</div>
				
				<div class="row wrapper white-bg page-heading no-padding-bottom">
					<div class="col-sm-4">
						<h2>
							<?php if($child->imagemTitulo): ?>
							<i class="fa <?php echo $child->imagemTitulo;?> fa-2x"></i>
							<?php endif; ?>
							<?php echo $child->titulo; ?>
						</h2>
					</div>
					<div class="col-sm-8">
						<?php echo $this->partial('layout/header_controls', $this); ?>
					</div>
				</div>
				
				<div class="row wrapper border-bottom white-bg page-heading">
					<div class="col-sm-12">
						<?php echo $this->partial('layout/breadcrumb', $this); ?>
					</div>
				</div>
				
				<?php if(!isset($child->disableBg)): ?>
				<div class="row">
					<div class="col-lg-12">
						<div class="wrapper wrapper-content">
							<div class="row">
								<div class="col-lg-12">
									<div class="ibox float-e-margins animated fadeInRightBig">
										<div class="ibox-content ibox-border">
											<?php echo $this->content; ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<?php else: ?>
				<?php echo $this->content; ?>
				<?php endif; ?>
				
				<div class="footer">
					<div>
						<strong>Copyright</strong>
						Company &copy; 2016<?php echo date("Y") == "2016" ? "" : " - " . date("Y"); ?>
					</div>
				</div>
			</div>
		</div>
		
		<?php echo $this->partial('layout/scripts', $this); ?>
		<?php echo $this->partial('layout/messages', $this); ?>
	</body>
</html>
