<!-- Mainly scripts -->
<script src="<?php echo $this->basePath(); ?>/inspinia/js/jquery-2.1.1.js"></script>
<script src="<?php echo $this->basePath(); ?>/inspinia/js/bootstrap.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/app/js/plugins/filterByData/filterByData.jquery.js"></script>
<script src="<?php echo $this->basePath(); ?>/inspinia/js/plugins/metisMenu/jquery.metisMenu.js"></script>
<script src="<?php echo $this->basePath(); ?>/inspinia/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

<!-- Mask -->
<script src="<?php echo $this->basePath(); ?>/app/js/plugins/mask/jquery.mask.min.js"></script>

<!-- i18n -->
<script src="<?php echo $this->basePath(); ?>/app/js/plugins/i18n/jquery.i18n.js"></script>
<script src="<?php echo $this->url('i18n/datatable'); ?>" type="text/javascript"></script>

<!-- Data Tables -->
<script src="<?php echo $this->basePath(); ?>/inspinia/js/plugins/dataTables/jquery.dataTables.js"></script>
<script src="<?php echo $this->basePath(); ?>/inspinia/js/plugins/dataTables/dataTables.bootstrap.js"></script>
<script src="<?php echo $this->basePath(); ?>/inspinia/js/plugins/dataTables/dataTables.responsive.js"></script>
<script src="<?php echo $this->basePath(); ?>/inspinia/js/plugins/dataTables/dataTables.tableTools.min.js"></script>

<!-- Custom and plugin javascript -->
<script src="<?php echo $this->basePath(); ?>/inspinia/js/inspinia.js"></script>
<script src="<?php echo $this->basePath(); ?>/inspinia/js/plugins/pace/pace.min.js"></script>

<!-- Select2 -->
<script src="<?php echo $this->basePath(); ?>/app/js/plugins/select2/select2.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/app/js/plugins/select2/select2_locale_<?php echo $this->translate('pt-BR'); ?>.js"></script>

<!-- iCheck script -->
<script src="<?php echo $this->basePath(); ?>/inspinia/js/plugins/iCheck/icheck.min.js"></script>

<!-- Toastr script -->
<script src="<?php echo $this->basePath(); ?>/inspinia/js/plugins/toastr/toastr.min.js"></script>

<!-- Switchery -->
<script src="<?php echo $this->basePath(); ?>/inspinia/js/plugins/switchery/switchery.js"></script>

<!-- Data picker -->
<script src="<?php echo $this->basePath(); ?>/inspinia/js/plugins/datapicker/bootstrap-datepicker.js"></script>
<script src="<?php echo $this->basePath(); ?>/inspinia/js/plugins/datapicker/locales/bootstrap-datepicker.pt-BR.min.js"></script>

<!-- Date range use moment.js same as full calendar plugin -->
<script src="<?php echo $this->basePath(); ?>/inspinia/js/plugins/fullcalendar/moment.min.js"></script>

<!-- Date range picker -->
<script src="<?php echo $this->basePath(); ?>/inspinia/js/plugins/daterangepicker/daterangepicker.js"></script>

<!-- Spinner -->
<script src="<?php echo $this->basePath(); ?>/app/js/plugins/spinner/jquery.spinner.min.js"></script>

<!-- ChartJS-->
<script src="<?php echo $this->basePath(); ?>/inspinia/js/plugins/chartJs/Chart.min.js"></script>

<!-- App script -->
<script src="<?php echo $this->basePath(); ?>/app/js/form-components.js"></script>
<script src="<?php echo $this->basePath(); ?>/app/js/app.js"></script>

<?php echo $this->headScript(); ?>
<?php echo $this->inlineScript() ?>