<footer>
	<div class="container">
		<img src="<?php echo $this->basePath(); ?>/www/img/footer-creditos.jpg" class="creditos" />
		<ul>
			<li><a href="#"><?php echo $this->translate('Contato'); ?></a></li>
			<li><a href="#"><?php echo $this->translate('Política de privacidade'); ?></a></li>
			<li><a href="#"><?php echo $this->translate('Termos de uso'); ?></a></li>
		</ul>
	</div>
</footer>

<div style='display:none'>
	<div id='o-que-e-box' class="modal-box">
		<img src="<?php echo $this->basePath(); ?>/www/img/o-que-e-cover.jpg" />
		<h3>O que é?</h3>
		<p>ESPAÇO DA PALAVRA é uma plataforma colaborativa que reúne práticas pedagógicas em escrita. Queremos conhecer, dar visibilidade e sistematizar experiências, projetos e metodologias que aproximam a escrita do universo de jovens estudantes.
		<br /><br />
		Através da escrita podemos construir e trocar experiências, criando outros modos de ser e de estar no mundo. A escrita é uma habilidade essencial para o desenvolvimento de potencialidades. Ela amplia nossa capacidade de perceber a realidade que nos cerca e interagir com ela de forma mais crítica e ativa.
		<br /><br />
		Neste site, você não encontrará conteúdos relacionados ao ensino formal da língua portuguesa (aulas de gramática ou aulas de história da literatura, por exemplo). A proposta do ESPAÇO DA PALAVRA é incentivar o desenvolvimento de práticas que apostam na criatividade, na inovação e no risco. Já que escrever é arriscar-se. É abrir-se para um processo intenso de descobertas e de incertezas, mas também de transformações profundas em nossa maneira de perceber e interagir com o mundo.</p>
	</div>
	<div id='como-funciona-box' class="modal-box">
		<img src="<?php echo $this->basePath(); ?>/www/img/como-funciona-cover.jpg" />
		<h3>como funciona?</h3>
		<p>Os professores podem publicar e compartilhar suas práticas pedagógicas, trocar informações com outros professores – formando redes e comunidades de aprendizado específicas – e conversar sobre os desafios e inquietações inerentes à prática em sala de aula.
		<br /><br />
		Para participar, acesse a seção <a href="<?php echo $this->url('publique'); ?>">PUBLIQUE</a>.</p>
	</div>
	<div id='porque-box' class="modal-box">
		<img src="<?php echo $this->basePath(); ?>/www/img/porque-cover.jpg" />
		<h3>Por que?</h3>
		<p>Estimular jovens estudantes a escrever, apropriando-se da linguagem de forma consciente, ativa e criativa é um grande desafio. Escrever é uma ação reflexiva, um ato de comunicação e de expressão. Escrever é uma forma de ocupar o mundo. Ou melhor, é uma forma de criar no mundo um espaço para nossas ideias e, a partir dessa ocupação, conviver com outras formas de ser e de pensar.
		<br /><br />
		Acreditamos que a escrita é um dispositivo capaz de transformar as pessoas. A partir do momento em que escrevem, elas tornam-se mais conscientes de si, dos outros e do lugar em que vivem. Acreditamos que todas as pessoas deveriam ter acesso a essa prática. Uma prática que é ação, reflexão, técnica, aprendizado e conhecimento.  Escrevemos para nos comunicar. Escrevemos porque existem outras pessoas interessadas em conhecer nosso universo simbólico e interagir com ele. Escrita é diálogo e diálogo gera convivência, conhecimento e solidariedade.
		<br /><br />
		Mas os espaços destinados à escrita – uma escrita viva, feita de incertezas e não apenas de certezas – são restritos. O ESPAÇO DA PALAVRA acredita que é importante incentivar educadores e estudantes a construírem coletivamente espaços para a existência e a resistência de outras formas de escrita. 
		</p>
	</div>
	<div id='quem-faz-box' class="modal-box">
		<h3>Quem faz?</h3>
		<img src="<?php echo $this->basePath(); ?>/www/img/quemfaz-placeholder.jpg" class="img-centered" />
	</div>
</div>