<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title><?php echo $this->translate('Espaço da Palavra'); ?></title>
<meta description="<?php echo $this->translate('ESPAÇO DA PALAVRA é uma plataforma colaborativa que reúne práticas pedagógicas em escrita. Queremos conhecer, dar visibilidade e sistematizar experiências, projetos e metodologias que aproximam a escrita do universo de jovens estudantes.'); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="<?php echo $this->basePath(); ?>/favicon.ico" type="image/x-icon">
<link rel="icon" href="<?php echo $this->basePath(); ?>/favicon.ico" type="image/x-icon">
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/www/styles/plugins.css">
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/www/styles/toastr/toastr.min.css">
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/www/styles/styles.css">