<script src="<?php echo $this->basePath(); ?>/www/js/plugins.js"></script>
<script src="<?php echo $this->basePath(); ?>/www/js/app.js"></script>
<script src="<?php echo $this->basePath(); ?>/www/js/toastr/toastr.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/www/js/input-mask/jquery.inputmask.bundle.min.js"></script>

<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-72765846-1', 'auto');
	ga('send', 'pageview');
</script>

<script src='//cdn.tinymce.com/4/tinymce.min.js'></script>
<script>
tinymce.init({
	selector: '#proposicao-conteudo',
	menubar:false,
	plugins: [
		"advlist autolink lists link image charmap print preview anchor",
		"searchreplace visualblocks code fullscreen",
		"insertdatetime media table contextmenu paste imagetools"
	],
	toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
	automatic_uploads: true
});
	
$(":input").inputmask();
</script>