<!doctype html>
<html class="no-js" lang="">
	<head>
		<?php echo $this->partial('frontend/layout/head', $this); ?>
  	</head>
	<body>
		<header>
			<div class="container">
				<div class="logo login">
					<h1>
						<a href="<?php echo $this->url('home'); ?>">
							<img src="<?php echo $this->basePath(); ?>/www/img/espaco-da-palavra.svg" alt="<?php echo $this->translate('Espaço da Palavra (Logo)'); ?>" />
						</a>
					</h1>
				</div>
			</div>
		</header>
		
		<?php echo $this->content; ?>
		
		<?php echo $this->partial('frontend/layout/scripts', $this); ?>
		<?php echo $this->partial('frontend/layout/messages', $this); ?>
	</body>
</html>