<?php
use Util\Util;
?>
<main class="login">
	<div class="container">
		<div class="col-full">
			<form action="" method="post" name="cadastroForm" enctype="multipart/form-data">
				<h2>Atualizar Cadastro</h2>
				
				<?php if(!Util::IsNullOrEmptyString($this->userIdentity()['usuario']->getImagemProfile())): ?>
				<div class="photo-profile">
					<img src="<?php echo $this->basePath(); ?>/uploads/<?php echo $this->userIdentity()['usuario']->getImagemProfile(); ?>">
				</div>
				<?php endif; ?>
				
				<?php echo $this->formLabel($this->form->get('nome')); ?>
				<?php echo $this->formElement($this->form->get('nome')); ?>
				<?php echo $this->formElementErrors()->render($this->form->get('nome')); ?>
				
				<?php echo $this->formLabel($this->form->get('email')); ?>
				<?php echo $this->formElement($this->form->get('email')); ?>
				<?php echo $this->formElementErrors()->render($this->form->get('email')); ?>
				
				<?php echo $this->formLabel($this->form->get('senha')); ?>
				<?php echo $this->formElement($this->form->get('senha')); ?>
				<?php echo $this->formElementErrors()->render($this->form->get('senha')); ?>
				
				<?php echo $this->formLabel($this->form->get('nova-senha')); ?>
				<?php echo $this->formElement($this->form->get('nova-senha')); ?>
				<?php echo $this->formElementErrors()->render($this->form->get('nova-senha')); ?>
				
				<?php echo $this->formLabel($this->form->get('confirmarsenha')); ?>
				<?php echo $this->formElement($this->form->get('confirmarsenha')); ?>
				<?php echo $this->formElementErrors()->render($this->form->get('confirmarsenha')); ?>
				
				<?php echo $this->formLabel($this->form->get('atuacao')); ?>
				<?php echo $this->formElement($this->form->get('atuacao')); ?>
				<?php echo $this->formElementErrors()->render($this->form->get('atuacao')); ?>
				
				<?php echo $this->formLabel($this->form->get('genero')); ?>
				<?php echo $this->formElement($this->form->get('genero')); ?>
				<?php echo $this->formElementErrors()->render($this->form->get('genero')); ?>
				
				<?php echo $this->formLabel($this->form->get('sobre')); ?>
				<?php echo $this->formElement($this->form->get('sobre')); ?>
				<?php echo $this->formElementErrors()->render($this->form->get('sobre')); ?>
				
				<?php echo $this->formLabel($this->form->get('foto')); ?>
				<?php echo $this->formElement($this->form->get('foto')); ?>
				<?php echo $this->formElementErrors()->render($this->form->get('foto')); ?>
				
				<?php echo $this->formElement($this->form->get('submit')); ?>
			</form>
		</div>
		
		<div class="clearthis"></div>
		
		<br />
		<br />
		<br />
		
		<div class="col-full">
			<h2>Minhas Proposições</h2>
			<table class="list">
				<?php foreach($this->lista as $l): ?>
				<tr>
					<td><?php echo $l->getNome(); ?></td>
					<td class="position"><a href="<?php echo $this->url('publique', array('idProposicao' => $l->getId())); ?>">Editar</a></td>
				</tr>
				<?php endforeach; ?>
			</table>
		</div>
	</div>
</main>