<aside class="filterbox">
	<div class="filter-full">
		<div class="content-filter">
			<ul>
				<li>
					<a href="<?php echo $this->url('categoria', array('tipo' => 'sensibilizacao')); ?>" class="applyfilter">
						<?php echo $this->translate('Sensibilização'); ?>
					</a>
				</li>
				<li>
					<a href="<?php echo $this->url('categoria', array('tipo' => 'jogos')); ?>" class="applyfilter">
						<?php echo $this->translate('Jogos'); ?>
					</a>
				</li>
				<li>
					<a href="<?php echo $this->url('categoria', array('tipo' => 'pratica-de-escrita')); ?>" class="applyfilter">
						<?php echo $this->translate('Prática de escrita'); ?>
					</a>
				</li>
			</ul>
		</div>
	</div>
</aside>
<main class="home">
	<div class="container">
		<?php echo $this->partial('foreachProposicao', array('lista' => $this->lista)); ?>
	</div>
</main>
