        <aside class="filterbox">

          <div class="filter-full">
            <div class="content-filter">
              <h2>Artistas da palavra</h2>
              <div class="col-full">
                <input type="checkbox" class="checkbox-artistas" id="livro-objeto">
                <label class="checkbox" for="livro-objeto">Livro objeto</label>
                <input type="checkbox" class="checkbox-artistas" id="intenvencao-urbana">
                <label class="checkbox" for="intenvencao-urbana">Intervenção urbana</label>
                <input type="checkbox" class="checkbox-artistas" id="performance">
                <label class="checkbox" for="performance">Performance</label>
                <input type="checkbox" class="checkbox-artistas" id="fantasia">
                <label class="checkbox" for="fantasia">Fantasia</label>
                <input type="checkbox" class="checkbox-artistas" id="jogos">
                <label class="checkbox" for="jogos">Jogos</label>
                <input type="checkbox" id="literatura-de-risco">
                <label class="checkbox" for="literatura-de-risco">Literatura de Risco</label>
                <input type="checkbox" id="vanguardas-artisticas">
                <label class="checkbox" for="vanguardas-artisticas">Vanguardas Artísticas</label>
                <input type="checkbox" id="poesia-visual">
                <label class="checkbox" for="poesia-visual">Poesia Visual</label>
                <input type="checkbox" id="arte-conceitual">
                <label class="checkbox" for="arte-conceitual">Arte Conceitual</label>
              </div>
            </div>
          </div>

        </aside>
        <main class="home">
          <div class="container">
            <ul>

              <a class="inlineartista item-artista" data-artista="livro-objeto" href="#viola-spolin">
                <li>
                  <h2>Viola Spolin </h2>
                  <div class="thumb">
                    <div class="hover-info">
                      <p>Norte Americana, professora, autora e diretora de teatro, Spolin se destaca na criação do teatro de improvisação, muito estudado ainda nos dias atuais.</p>
                    </div>
                    <img src="<?php echo $this->basePath(); ?>/www/img/artistas/viola-spolin-thumb.jpg" />
                  </div>
                </li>
              </a>
              <a class="inlineartista item-artista" data-artista="livro-objeto" href="#raymond-queneau">
                <li>
                  <h2>Raymond Queneau </h2>
                  <div class="thumb">
                    <div class="hover-info">
                      <p>Surrealista, romancista, ensaísta e poeta francês, Queneau é conhecido por sua obra prima Exercícios de estilo, um livro aparentemente simplório que narra a história de um homem que se encontro, no mesmo dia, com uma mesma pessoa.</p>
                    </div>
                    <img src="<?php echo $this->basePath(); ?>/www/img/artistas/queneau-thumb.jpg" />
                  </div>
                </li>
              </a>
              <a class="inlineartista item-artista" data-artista="livro-objeto" href="#tristan-tzara">
                <li>
                  <h2>Tristan Tzara  </h2>
                  <div class="thumb">
                    <div class="hover-info">
                      <p>Uma das personalidades do movimento DadaístaTristan Tzara é um pseudônimo adotado pelo poeta Samuel Rosenstock e significa “triste terra”, um protesto contra o tratamento que os judeus sofreram na primeira guerra</p>
                    </div>
                    <img src="<?php echo $this->basePath(); ?>/www/img/artistas/tristan-thumb.jpg" />
                  </div>
                </li>
              </a>
            </ul>
          </div>
          <div style='display:none'>
      			<div id='viola-spolin' class="modal-box artista-box">
              <div class="artista-galeria">
                <div class="palco-galeria">
                  <img class="galerry-stage" src="<?php echo $this->basePath(); ?>/www/img/artistas/viola-spolin.jpg" />
                </div>
                <!--<ul class="galeria-menu">
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artistas/arnaldo-antunes.jpg" /></li>
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artista-palco-placeholder.jpg" /></li>
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artista-palco-placeholder.jpg" /></li>
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artista-palco-placeholder.jpg" /></li>
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artista-palco-placeholder.jpg" /></li>
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artista-palco-placeholder.jpg" /></li>
                </ul>-->
              </div>
              <div class="artista-conteudo">
                <h3>Viola Spolin</h3>
                <div class="artista-info">
                  <ul>
                    <li>Nascimento: <span>07 de Novembro de 1906, Chicago – Estados Unidos.</span></li>
                    <li>Falecimento: <span>22 de Novembro de 1994, Los Angelis – Estados Unidos.</span></li>
                  </ul>
                </div>
                <div class="artista-social">
                </div>
                <h4>Análise</h4>
                <p>Norte Americana, professora, autora e diretora de teatro, Spolin se destaca na criação do teatro de improvisação, muito estudado ainda nos dias atuais. Sua principal obra Jogos Teatrais, estuda a metodologia da encenação e do ensino do teatro dentro e fora das escolas. Criadora da blablação – jogo vocal no qual as pessoas substituem os sons das palavras por sons aleatórios. A blablação desenvolve a expressão corporal a partir da experimentação sonora com as palavras.
                </p>
                <h4>Obras publicadas</h4>
                <ul class="obras">
                  <li>A improvisação para o Teatro, 1978</li>
                  <li>O Jogo Teatral no Livro do Diretor, 2000 </li>
                  <li>Jogos Teatrais – O fichário de Viola Spolin, 2000</li>
                  <li>Jogos Teatrais na Sala de Aula, 2007 </li>
                </ul>
              </div>
      			</div>
            <div id='raymond-queneau' class="modal-box artista-box">
              <div class="artista-galeria">
                <div class="palco-galeria">
                  <img class="galerry-stage" src="<?php echo $this->basePath(); ?>/www/img/artistas/queneau.jpg" />
                </div>
                <!--<ul class="galeria-menu">
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artistas/arnaldo-antunes.jpg" /></li>
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artista-palco-placeholder.jpg" /></li>
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artista-palco-placeholder.jpg" /></li>
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artista-palco-placeholder.jpg" /></li>
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artista-palco-placeholder.jpg" /></li>
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artista-palco-placeholder.jpg" /></li>
                </ul>-->
              </div>
              <div class="artista-conteudo">
                <h3>Raymond Queneau</h3>
                <div class="artista-info">
                  <ul>
                    <li>Nascimento: <span>21 de Fevereiro de 1903, Le Havre – França.</span></li>
                    <li>Falecimento: <span>25 de Outubro de 1976, Neuilly-sur-Seine – França.</span></li>
                  </ul>
                </div>
                <div class="artista-social">
                </div>
                <h4>Análise</h4>
                <p>Surrealista, romancista, ensaísta e poeta francês, Queneau é conhecido por sua obra prima Exercícios de estilo, um livro aparentemente simplório que narra a história de um homem que se encontro, no mesmo dia, com uma mesma pessoa. O autor investe na experiência de imersão de pesquisa de estilo, quando escreve esta mesma história 99 vezes, testando os limites da expressão textual dos gêneros.
                </p>
                <h4>Obras publicadas</h4>
                <ul class="obras">
                  <li>Zazie no Metrô</li>
                  <li><a href="https://monoskop.org/images/b/b0/Queneau_Raymond_Exercicios_de_estilo.pdf" target="_blank">Exercícios de Estilo</a></li>
                </ul>
              </div>
            </div>
            <div id='tristan-tzara' class="modal-box artista-box">
              <div class="artista-galeria">
                <div class="palco-galeria">
                  <img class="galerry-stage" src="<?php echo $this->basePath(); ?>/www/img/artistas/tristan.jpg" />
                </div>
                <!--<ul class="galeria-menu">
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artistas/arnaldo-antunes.jpg" /></li>
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artista-palco-placeholder.jpg" /></li>
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artista-palco-placeholder.jpg" /></li>
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artista-palco-placeholder.jpg" /></li>
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artista-palco-placeholder.jpg" /></li>
                  <li><img class="gallery-item" src="<?php echo $this->basePath(); ?>/www/img/artista-palco-placeholder.jpg" /></li>
                </ul>-->
              </div>
              <div class="artista-conteudo">
                <h3>Tristan Tzara </h3>
                <div class="artista-info">
                  <ul>
                    <li>Nascimento: <span>1896, Romênia</span></li>
                    <li>Falecimento: <span>1963, Paris</span></li>
                  </ul>
                </div>
                <div class="artista-social">
                </div>
                <h4>Análise</h4>
                <p>Uma das personalidades do movimento DadaístaTristan Tzara é um pseudônimo adotado pelo poeta Samuel Rosenstock e significa “triste terra”, um protesto contra o tratamento que os judeus sofreram na primeira guerra. Autor do manifesto Dadaísta, Tzara critica os valores e a linguagem do homem em suas obras e propõe o nonsense como forma de criação poética.
                </p>
                <h4>Como fazer um poema dadaísta: </h4>
                <ul class="obras">
                  <li>Pegue num jornal.</li>
                  <li>Pegue numa tesoura.</li>
                  <li>Escolha no jornal um artigo com o comprimento que pretende dar ao seu poema.</li>
                  <li>Recorte o artigo.</li>
                  <li>Em seguida, recorte cuidadosamente as palavras que compõem o artigo e coloque-as num saco.</li>
                  <li>Agite suavemente.</li>
                  <li>Depois, retire os recortes uns a seguir aos outros.</li>
                  <li>Transcreva-os escrupulosamente pela ordem que eles saíram do saco.</li>
                  <li>O poema parecer-se-á consigo.</li>
                  <li>E você será um escritor infinitamente original, de uma encantadora sensibilidade, ainda que incompreendido pelas pessoas vulgares.</li>

                </ul>
              </div>
            </div>
          </div>
        </main>