        <aside class="filterbox">

          <div class="filter-full leitura">
            <div class="content-filter">
              <h2>Dicas de Leitura</h2>
              <div class="col-full ">
                <input type="checkbox" class="checkbox-leitura" id="a-c">
                <label class="checkbox" for="a-c">a-c</label>
                <input type="checkbox" class="checkbox-leitura" id="d-f">
                <label class="checkbox" for="d-f">d-f</label>
                <input type="checkbox" class="checkbox-leitura" id="g-i">
                <label class="checkbox" for="g-i">g-i</label>
                <input type="checkbox" class="checkbox-leitura" id="j-l">
                <label class="checkbox" for="j-l">j-l</label>
                <input type="checkbox" class="checkbox-leitura" id="m-n">
                <label class="checkbox" for="m-n">m-n</label>
                <input type="checkbox" class="checkbox-leitura" id="p-r">
                <label class="checkbox" for="p-r">p-r</label>
                <input type="checkbox" class="checkbox-leitura" id="s-u">
                <label class="checkbox" for="s-u">s-u</label>
                <input type="checkbox" class="checkbox-leitura" id="w-x">
                <label class="checkbox" for="w-x">w-x</label>
                <input type="checkbox" class="checkbox-leitura" id="y-z">
                <label class="checkbox" for="y-z">y-z</label>
              </div>
            </div>
          </div>

        </aside>
        <main class="home">
          <div class="container">
            <p class="about-sectioin-leitura">Este espaço é destinado a referências de natureza diversas - textos, vídeos, sites e

            ou/trabalhos artísticos - que podem ajudar o professor no processo de pesquisa e

            planejamento de atividades. Ele foi organizado a partir de um pensamento transdisciplinar. Ou

            seja, outros saberes e reflexões que não apenas os relacionados à literatura e ao texto, mas

            que podem contribuir para a formação permanente dos educadores que atuam no campo da

            escrita.</p>
            <ul>

              <a class="item-leitura" data-leitura="s-u" href="http://www.ubu.com/" target="_blank">
                <li>
                  <h2>Ubu.com</h2>
                  <div class="thumb">
                    <div class="hover-info">
                      <p>Uma descrição sobre o item.</p>
                    </div>
                    <img src="<?php echo $this->basePath(); ?>/www/img/leitura/ubu-thumb.jpg" />
                  </div>
                </li>
              </a>

              <a class="item-leitura" data-leitura="g-i" href="http://homoliteratus.com/" target="_blank">
                <li>
                  <h2>Homo Literatus</h2>
                  <div class="thumb">
                    <div class="hover-info">
                      <p>Uma descrição sobre o site.</p>
                    </div>
                    <img src="<?php echo $this->basePath(); ?>/www/img/leitura/homo-literatus.jpg" />
                  </div>
                </li>
              </a>

              <a class="item-leitura" data-leitura="d-f" href="http://estrategiasnarrativas.org/" target="_blank">
                <li>
                  <h2>Estratégias Narrativas</h2>
                  <div class="thumb">
                    <div class="hover-info">
                      <p>Uma descrição sobre o site.</p>
                    </div>
                    <img src="<?php echo $this->basePath(); ?>/www/img/leitura/estrategias-narrativas.jpg" />
                  </div>
                </li>
              </a>



            </ul>
          </div>

        </main>