        <main class=" home ">
          <div class="container">
            <h2>Metodologias</h2>
            <ul>
              <a class="inline item-artista" data-artista="livro-objeto" href="#metodologia-porque">
                <li>
                  <h2>POR QUE QUEREMOS QUE OS ESTUDANTES ESCREVAM? </h2>
                  <div class="thumb">
                    <img src="<?php echo $this->basePath(); ?>/www/img/metodologias/porque.jpg" />
                  </div>
                </li>
              </a>

              <a class="inline item-artista" data-artista="livro-objeto" href="#metodologia-conhecimento">
                <li>
                  <h2>ESCRITA PARA O CONHECIMENTO</h2>
                  <div class="thumb">
                    <img src="<?php echo $this->basePath(); ?>/www/img/metodologias/conhecimento.jpg" />
                  </div>
                </li>
              </a>

              <a class="inline item-artista" data-artista="livro-objeto" href="#metodologia-autonomia">
                <li>
                  <h2>ESCRITA PARA A AUTONOMIA</h2>
                  <div class="thumb">
                    <img src="<?php echo $this->basePath(); ?>/www/img/metodologias/autonomia.jpg" />
                  </div>
                </li>
              </a>

              <a class="inline item-artista" data-artista="livro-objeto" href="#metodologia-visibilidade">
                <li>
                  <h2>ESCRITA PARA A VISIBILIDADADE</h2>
                  <div class="thumb">
                    <img src="<?php echo $this->basePath(); ?>/www/img/metodologias/visibilidade.jpg" />
                  </div>
                </li>
              </a>

              <a class="inline item-artista" data-artista="livro-objeto" href="#metodologia-professor">
                <li>
                  <h2>REPENSANDO O PAPEL DO PROFESSOR</h2>
                  <div class="thumb">
                    <img src="<?php echo $this->basePath(); ?>/www/img/metodologias/professor.jpg" />
                  </div>
                </li>
              </a>

              <a class="inline item-artista" data-artista="livro-objeto" href="#metodologia-textos">
                <li>
                  <h2>AVALIANDO TEXTOS: O PROFESSOR COMO EDITOR</h2>
                  <div class="thumb">
                    <img src="<?php echo $this->basePath(); ?>/www/img/metodologias/texto.jpg" />
                  </div>
                </li>
              </a>

              <a class="inline item-artista" data-artista="livro-objeto" href="#metodologia-proposicao">
                <li>
                  <h2>AVALIANDO A PROPOSIÇÃO: O DESLOCAMENTO COMO OBJETIVO</h2>
                  <div class="thumb">
                    <img src="<?php echo $this->basePath(); ?>/www/img/metodologias/proposicao.jpg" />
                  </div>
                </li>
              </a>


            </ul>
            <div style="display:none">
              <div id='metodologia-porque' class="modal-box">
                <h3>POR QUE QUEREMOS QUE OS ESTUDANTES ESCREVAM?</h3>
                <p>A escrita não é apenas instrumento. Ela é uma ação que comporta dois movimentos aparentemente contraditórios, mas fundamentais para o processo de aprendizado e subjetivação das pessoas. Um movimento para dentro (reflexivo) e outro movimento para fora (dialógico). Quando escrevemos, precisamos nos equilibrar nessa fronteira – às vezes tensa, porque sempre incerta – de pensar e simultaneamente colocar nosso pensamento em dúvida.
                <br /><br />
                É nesse circuito que a escrita – enquanto construção simbólica de homens e mulheres – produz memória, arte, história, poesia e, também, conhecimento. Escrever implica colocar em funcionamento uma série de habilidades e sensibilidades que nos ajudam a conhecer, a aprender e a compreender o mundo.
                <br /><br />
                Escrevemos para organizar nossos pensamentos. Escrevemos para dar um destino às nossas inquietações, para que elas possam ser enunciadas e expressas, para encontrar nosso lugar no mundo. Escrever produz CONHECIMENTO, AUTONOMIA E VISIBILIDADE. Acreditamos que essas qualidades nos ajudam a potencializar os sentidos da educação e é a partir dessa perspectiva -  escrita como processo de descoberta -  que convidamos professores e estudantes a vivenciar a experiência da escrita.
                </p>
              </div>
              <div id='metodologia-conhecimento' class="modal-box">
                <h3>ESCRITA PARA O CONHECIMENTO</h3>
                <p>Conhecer amplia nossa relação com o mundo, pois multiplica as informações que temos sobre ele (as pessoas, os lugares, as ideias). Mas conhecer é uma ação dialógica. As pessoas precisam estar implicadas no processo do conhecimento para que este tenha ressonância em seus contextos de vida. Neste sentido, conhecer deve mobilizar a curiosidade e o interesse particular dos indivíduos.
                <br /><br />
                Podemos conhecer o mundo de várias formas e escrever é uma delas. A escrita não pode ser apenas o fim dos processos de aprendizado. A escrita é também o meio. Ela é uma habilidade que promove inúmeras descobertas. Podemos usar a escrita como forma de aproximação, de observação, de análise, de comparação, de investigação, de questionamento, de crítica, de criação artística.
                <br /><br />
                Quando promovemos UMA ESCRITA PARA O CONHECIMENTO queremos potencializar a criatividade dos estudantes para que eles possam se apropriar desse recurso (a escrita é também uma habilidade e um saber) e experimentar novas formas de conhecer e aprender.
                </p>
                <h4>COMO FAZER:</h4>
                <ul>
                  <li>Os professores podem propor práticas que desnaturalizem processos cotidianos e “naturais” como ler e escrever, provocando deslocamentos concretos da percepção e dos usos do material verbal.</li>
                  <li>Desenvolver aulas sobre a história da escrita, história da leitura e história do livro, ressaltando os avanços técnicos de cada momento histórico e suas implicações sociais, culturais e políticas na vida das pessoas.</li>
                  <li>Mostrar processos de fabricação do papel e do livro. Os estudantes podem construir um pequeno livro/caderno a partir de técnicas simples de encadernação.</li>
                  <li>Conhecer técnicas de impressão e reprodução de texto e imagem (gravura, mimeógrafo, xerox, impressão digital) e realizar experiências poéticas com essas técnicas..</li>
                  <li>Propor discussões que problematizem o caráter político da escrita. A escrita também pode ser ferramenta de manipulação?</li>
                  <li>Pesquisar diferentes tipos de escrita e seus usos. Os estudantes podem produzir etnografias urbanas, observando e escrevendo sobre seus respectivos contextos: a família, a escola, a igreja.</li>
                  <li>Ver SENSIBILIZAÇÃO + JOGOS + REFERÊNCIAS</li>
                </ul>

                <h4>DICA DE FILME:</h4>
                <p>O documentário Língua – Vidas em português é uma ótima referência para entender a abrangência e as particularidades da língua portuguesa. O filme aborda a riqueza cultural dessa língua falada em mais de 17 países do mundo e como cada lugar incorpora matizes culturais específicos nos usos que faz da língua. Disponível em: <br />
                <a href="https://www.youtube.com/watch?v=JBmLzbjmhhg" target="_blank">https://www.youtube.com/watch?v=JBmLzbjmhhg</a></p>
                </p>
              </div>
              <div id='metodologia-autonomia' class="modal-box">
                <h3>ESCRITA PARA A AUTONOMIA</h3>
                <p>A autonomia está relacionada com a possibilidade de pensar e agir de forma livre e independente. Para Paulo Freire, a função mais urgente da educação é promover a autonomia das pessoas. Ser autônomo significa ser responsável pela construção da própria trajetória de vida e não “objeto” do determinismo econômico e social. A autonomia fortalece a identidade e a consciência de que é preciso atuar no mundo a partir de um lugar ativo e crítico.
                <br /><br />
                A escrita promove a autonomia já que ela é o exercício da auto-reflexão e do questionamento por excelência. Escrever é um processo profundo de subjetivação. Ao escrever estamos implicados na tarefa de organizar e reavaliar nossa opinião sobre o mundo, sobre nós mesmos e sobre as pessoas. A escrita promove deslocamento, solidariedade, incerteza e também descobertas.
                <br /><br />
                Quando promovemos UMA ESCRITA PARA A AUTONOMIA queremos potencializar a independência dos estudantes para que eles possam ser mais conscientes e críticos em relação e si mesmos e ao mundo.</p>

                <h4>COMO FAZER:</h4>
                <ul>
                  <li>Escrita de manifestos a partir de problemas concretos vivenciados pelos estudantes (racismo, discriminação sexual e de gênero, homofobia, machismo, violência urbana, mobilidade urbana).</li>
                  <li>Proposição Autorretrato. Os estudantes são convidados a escrever sobre si mesmos a partir da observação cuidadosa de aspectos íntimos e pessoais, construindo um autorretrato escrito.</li>
                  <li>Escrever diários, nos quais os estudantes podem anotar pensamentos e fatos do dia-a-dia e refletir– a partir da escrita – sobre esses acontecimentos.</li>
                  <li>Escrever um Memorial. Os estudantes são convidados a analisar retrospectivamente a própria vida (sonhos, interesses, conquistas) e escrever sobre ela. Também podem fazer o exercício inverso e projetar o futuro. </li>
                </ul>
              </div>
              <div id='metodologia-visibilidade' class="modal-box">
                <h3>ESCRITA PARA A VISIBILIDADADE</h3>
                <p>A visibilidade é a capacidade que grupos e indivíduos têm de ocupar os espaços simbólicos de uma sociedade e serem percebidos como sujeitos singulares. No Brasil, diversos grupos e indivíduos tiveram suas histórias – sistematicamente – esquecidas, destruídas ou silenciadas. A visibilidade é um processo político: reconhecer a importância de todas essas narrativas e experiências e criar espaços de visibilidade para elas.
                <br /><br />
                A escrita produz e promove visibilidade, já que através dela podemos conhecer e reconstruir histórias individuais e coletivas. Escrever a partir de um lugar político, a partir de um contexto social e cultural específico, a partir de uma raça e de um gênero é um a forma de lutar por visibilidade.
                <br /><br />
                Quando pensamos em visibilidade pensamos também em convivência, ampliamos nosso conhecimento acerca do outro e aprendemos a conviver (a partir de nossas diferenças) de um jeito mais ético, solidário e múltiplo. A multiplicidade de narrativas nos salva da armadilha da “história única”. Torna-nos seres mais conscientes e tolerantes, implicados efetivamente no convívio ético com a diferença.
                <br /><br />
                Quando promovemos UMA ESCRITA PARA A VISIBILIDADE  queremos potencializar a identidade e a subjetividade dos estudantes para que eles possam produzir, conhecer e refletir sobre o lugar que ocupam no mundo.</p>
                <h4>DICA DE LEITURA:</h4>
                <p>Da grafia-desenho de minha mãe um dos lugares de nascimento da minha escrita, Conceição Evaristo. Disponível
                em: <a href="http://nossaescrevivencia.blogspot.com.br/2012/08/da-grafia-desenho-de-minha-mae-um-dos.html" target="_blank">http://nossaescrevivencia.blogspot.com.br/2012/08/da-grafia-desenho-de-minha-mae-um-dos.html</a></p>

              </div>
              <div id='metodologia-professor' class="modal-box">
                <h3>REPENSANDO O PAPEL DO PROFESSOR</h3>
                <p>Escrever sempre foi compreendido como um processo solitário, centrado, exclusivamente, na figura do autor (sua biografia, suas leituras e referências, seu universo interior). Essa concepção vigorou durante muito tempo e ainda permeia a cabeça de alguns leitores e escritores mais românticos.
                <br /><br />
                A partir da metade do século 20, alguns teóricos da literatura, entre eles o francês Roland Barthes, propuseram uma nova abordagem do texto literário. Ao decretar que o autor estava morto, Barthes afirmou a importância de pensarmos as diversas camadas de sentido e significação presentes em um texto para além da intenção do autor.
                <br /><br />
                A intertextualidade – que é a forma como um texto dialoga com outros textos - e o papel do leitor na construção do sentido do texto são duas características fundamentais que nos ajudam a compreender que escrever é um processo coletivo, um procedimento que convida e dialoga com outros textos, vozes e agentes.
                <br /><br />
                A partir dessa perspectiva – da escrita como processo coletivo –  queremos problematizar o papel do professor e a relação que ele estabelece tanto com os textos que lê e avalia quanto com os estudantes.
                <br /><br />
                Os estudantes devem entender que não existem regras na construção de um texto expressivo.  Cada texto é um processo, cada texto solicita uma estratégia narrativa. Muitas vezes, o estudante só irá entender a estratégia que está adotando quando finalizar o texto. O estudante precisa ter consciência da dimensão ativa e responsável que o ato de escrever demanda e apropriar-se desse espaço.
                <br /><br />
                Os professores devem respeitar o processo de cada estudante na construção do texto, evitando comparações e/ou avaliações de desempenho pautadas por parâmetros externos. O estudante deve ser avaliado a partir dos próprios avanços, do próprio percurso de escrita. Entender o processo como resultado desloca o foco da avaliação tradicional para a percepção de que cada indivíduo é único em seu percurso de descoberta e construção do próprio aprendizado.
                </p>

              </div>
              <div id='metodologia-textos' class="modal-box">
                <h3>AVALIANDO TEXTOS: O PROFESSOR COMO EDITOR</h3>
                <p>Escrever é quase sempre um mergulho em uma realidade paralela, imaginária, fora do tempo da vida prática e útil. Entenda a sala de aula como um ateliê, um laboratório, um espaço de criação e experimentação e principalmente, repense o seu papel. A partir do momento que o professor transforma-se em editor e não em revisor, ele estabelece um diálogo muito mais vivo e produtivo com os estudantes e com os textos que eles produzem.
                <br /><br />
                O editor trabalha em parceria. O texto deve ser compreendido como um trabalho coletivo. Nessa nova lógica – que suspende as avaliações tradicionais – o editor é uma espécie de leitor especializado que deve mostrar ao estudante as potencialidades e fragilidades do texto. Após as observações, dicas, referências do professor/editor, os estudantes devem reescrever o texto buscando sempre potencializar os sentidos que deseja alcançar.</p>

              </div>
              <div id='metodologia-proposicao' class="modal-box">
                <h3>AVALIANDO A PROPOSIÇÃO: O DESLOCAMENTO COMO OBJETIVO</h3>
                <p>Editar não é avaliar, mas isso não significa que não seja importante avaliar a atividade. Mas atenção, avaliar a atividade é diferente de avaliar o texto. A avaliação clássica – aquela que compara e que estabelece metas – não deveria ser aplicada à produção textual de cada estudante.
                <br /><br />
                No entanto, é importante que toda atividade de produção de texto seja, ao final, avaliada pelos participantes. Os professores devem pensar estratégias de avaliação que busquem problematizar as questões trabalhadas na atividade, o processo, os resultados e a participação de cada estudante, lembrando-se sempre que avaliar é, principalmente, se auto-avaliar.
                <br /><br />
                Acreditamos que o ponto mais importante a ser analisado é a medida de deslocamento dos estudantes. Isso significa observar o quanto eles conseguiram se modificar a partir do texto que escreveram e como o texto e o processo contribuíram para trazer questionamentos, reflexões, outros pontos de vista, tomadas de consciência e percepções sobre si mesmos ou sobre o tema.
                </p>

              </div>
            </div>
          </div>
        </main>